const USER_PARAMS_IS_NOT_EMPTY = '必传参数不能为空~'
const USER_EMAIL_CODE_IS_NOT_MATCH = '邮箱验证码不正确~'
const USER_PHONE_NUMBER_CODE_IS_NOT_MATCH = '手机号验证码不正确'
const USER_USERNAME_IS_NOT_EXISTS = '用户名不存在'
const USER_CAP_IS_NOT_MATCH = '验证码不正确'
const PASSWORD_IS_NOT_RIGHT = '密码不正确'
const TOKEN_IS_INVALID = 'token无效'

module.exports = {
  USER_PARAMS_IS_NOT_EMPTY,
  USER_EMAIL_CODE_IS_NOT_MATCH,
  USER_PHONE_NUMBER_CODE_IS_NOT_MATCH,
  USER_USERNAME_IS_NOT_EXISTS,
  USER_CAP_IS_NOT_MATCH,
  PASSWORD_IS_NOT_RIGHT,
  TOKEN_IS_INVALID
}