const USER_PARAMS_IS_NOT_EMPTY = '必传参数不能为空~'
const USER_EMAIL_CODE_IS_NOT_MATCH = '邮箱验证码不正确~'
const USER_PHONE_NUMBER_CODE_IS_NOT_MATCH = '手机号验证码不正确'

module.exports = {
  USER_PARAMS_IS_NOT_EMPTY,
  USER_EMAIL_CODE_IS_NOT_MATCH,
  USER_PHONE_NUMBER_CODE_IS_NOT_MATCH
}